<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__vfb-3</name>
   <tag></tag>
   <elementGuidId>6cbe9bb4-a04f-41de-8256-c3e680e47c32</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='vfb-3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#vfb-3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d0f30b25-9226-494d-aac8-7572eaa458f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c4c7570b-589e-48d4-a46a-e576789c0652</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>vfb-3</value>
      <webElementGuid>a21a2b07-c5f8-461a-8917-c3eb34ef5951</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>vfb-3</value>
      <webElementGuid>bd11ceaf-f76c-4d62-9125-ebae799d3ecf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vfb-text  vfb-medium  required {digits:true,maxlength:2,minlength:2} </value>
      <webElementGuid>b3927663-e419-45c3-9db8-fc00f7dc29fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vfb-3&quot;)</value>
      <webElementGuid>a334ed8e-a6bb-44f2-ae98-99305034e9e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='vfb-3']</value>
      <webElementGuid>f286bae6-46f2-48f0-99aa-0ad6fb9a8592</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='item-vfb-2']/ul/li/span/input</value>
      <webElementGuid>243202b9-b2a8-4f1c-bb0b-52aee1619f9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[2]/ul/li/span/input</value>
      <webElementGuid>c876e2a0-b5b1-4461-b271-1df12aa8bdb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'vfb-3' and @id = 'vfb-3']</value>
      <webElementGuid>b208010d-55f0-4a5e-8197-e64cf5b22b85</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
