<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_This box is for spam protection - str_2dcb9b</name>
   <tag></tag>
   <elementGuidId>33c57e8e-e9bc-4776-8043-cf1b1298bafe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='vfb-4']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#vfb-4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>303a9dc8-8a78-45b7-9c21-91e695b333b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>17fc14d6-03c3-4b40-841f-b606fc921370</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>vfb-submit</value>
      <webElementGuid>b14ddeb8-542c-4eee-872a-2a954239e32e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>vfb-4</value>
      <webElementGuid>e6ae3e6c-7e36-4001-b482-874c0953b47c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Submit</value>
      <webElementGuid>064cb988-f431-4107-bc13-9947dc24e575</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vfb-submit </value>
      <webElementGuid>6933cedd-0c99-4601-add7-79d0ecacbfde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vfb-4&quot;)</value>
      <webElementGuid>7314996c-6559-4d41-a47b-97ea51532bc7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='vfb-4']</value>
      <webElementGuid>a0829840-7f59-4c07-abe9-d709c4f368cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='item-vfb-4']/input</value>
      <webElementGuid>e50b0a5b-9c96-4626-9a04-486818d806d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/input</value>
      <webElementGuid>f6b5ba4f-40e9-4777-a413-ddf22a311fd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'vfb-submit' and @id = 'vfb-4']</value>
      <webElementGuid>3fffb480-f604-424c-9cb1-cf8682b7d9ef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
